<?php

namespace Request\Client;

use Ssitdikov\MediascoutApiClient\Object\Client\Client;
use Ssitdikov\MediascoutApiClient\Query\Client\ClientQuery;
use Ssitdikov\MediascoutApiClient\Request\Client\CreateClientRequest;
use PHPUnit\Framework\TestCase;

use function PHPUnit\Framework\assertSame;

class CreateClientRequestTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    public function testGetParam(): void
    {
        $name = 'БО';
        $inn = '123456789012';
        $client = new Client($name, $inn);
        $client_query = new ClientQuery($client);
        $create_client_request = new CreateClientRequest($client_query);
        assertSame(
            json_encode(['headers' => ['Content-Type' => 'application/json'], 'json' => []]),
                   json_encode($create_client_request->getParams())
        );
    }
}
